Bug fixes and code overhaul

diff --git a/jcomp b/jcomp
--- a/jcomp
+++ b/jcomp
@@ -5,92 +5,167 @@
 ## @author Spencer Imbleau
 ## @version July 2019
 
+# Print usage for the program
+print_usage() {
+	echo "Usage: \"jcomp\""
+	return 1
+}
+
 # Check the classpath was set and exists
-if [ -z '$CLASSPATH' ]
-then
-	echo "CLASSPATH not set. Exiting..."
-	exit 1
-fi
-
-# Index needed locations
-STRUCTURE_PATH=$(realpath $CLASSPATH/..)
-SOURCE_PATH=$(realpath $CLASSPATH/../src)
-BIN_PATH=$(realpath $CLASSPATH)
-
-# Check that our classpath folder is named 'bin'
-if [ ! ${BIN_PATH: -4} == "/bin" ]
-then
-	echo "$BIN_PATH must be a folder named bin."
-	echo "You should initiate jsrc on your source folder or set your classpath."
-	exit 1
-fi
-
-# Check there exists a /src/ directory to compile java files from
-if [ ! -d $SOURCE_PATH ]
-then
-	echo -n "$SOURCE_PATH does not exist. Create it now? (y/N) > "
-	
-	# Create 
-	read -n1 input
-	echo ""
-	if [ $input == "y" ] || [ $input == "Y" ]
+#
+# @returns 0 if $CLASSPATH was set and exists conventionally, 1 otherwise
+check_bin_path() {
+	# Check if classpath was set
+	if [ -z '$CLASSPATH' ]
 	then
-		echo "Creating $SOURCE_PATH"
-		mkdir $SOURCE_PATH
-		if [ $? -ne 0 ]
-		then
-			echo "Could not create $SOURCE_PATH. Privilege error."
-			exit 1
-		fi
+		echo "[ERROR] CLASSPATH not set."
+		return 1
 	else
-		echo "You must obey standard conventions to use this program."
-		exit 1
+		return 0
 	fi
-fi
-
-# Check there exists a /bin/ directory to export the .class files 
-if [ ! -d $BIN_PATH ] 
-then
-	echo -n "$BIN_PATH does not exist. Create one now? (y/N) > "
 	
-	# Create 
-	read -n1 input
-	echo ""
-	if [ $input == "y" ] || [ $input == "Y" ]
+	BIN_PATH=$(realpath $CLASSPATH 2> /dev/null)
+	
+	# Check that our classpath is named 'bin'
+	if [ ! ${BIN_PATH: -4} == "/bin" ]
 	then
-		echo "Creating $BIN_PATH"
-		mkdir $BIN_PATH
-		if [ $? -ne 0 ]
-		then
-			echo "Could not create $BIN_PATH. Privilege error."
-			exit 1
-		fi
-	else
-		echo "You must obey standard conventions to use this program."
-		exit 1
+		echo "[ERROR] $BIN_PATH must be a folder named bin. You should initiate jsrc on your source folder."
+		return 1
 	fi
-fi
 
-## Gather any java files within the classpath
-list=$(find $SOURCE_PATH -name "*.java")
+	# Check that the classpath is a directory 
+	if [ ! -d $BIN_PATH ] 
+	then
+		echo -n "$BIN_PATH does not exist. Create one now? (y/N) > "
+		# Create 
+		read -n1 input
+		echo ""
+		if [ $input == "y" ] || [ $input == "Y" ]
+		then
+			mkdir $BIN_PATH
+			if [ $? -ne 0 ]
+			then
+				echo "[ERROR] Could not create $BIN_PATH. Privilege error."
+				return 1
+			fi
+		else
+			echo "[ERROR] You must obey standard conventions to use this program."
+			return 1
+		fi
+	fi
 
-if [ -z "$list" ]
+	return 0
+}
+
+
+# Check the source directory exists
+#
+# @returns 0 if the conventional source directory exists, 1 otherwise
+check_source_path() {
+	SOURCE_PATH=$(realpath $CLASSPATH/../src 2> /dev/null)
+	# Check there exists a /src/ directory to compile java files from
+	if [ ! -d $SOURCE_PATH ]
+	then
+		# Ask user to create 
+		echo -n "$SOURCE_PATH does not exist. Create it now? (y/N) > "
+		read -n1 input
+		echo ""
+		if [ $input == "y" ] || [ $input == "Y" ]
+		then
+			mkdir $SOURCE_PATH
+			if [ $? -ne 0 ]
+			then
+				echo "[ERROR] Could not create $SOURCE_PATH. Privilege error."
+				return 1
+			fi
+		else
+			echo "[ERROR] You must obey standard conventions to use this program."
+			return 1
+		fi
+	fi
+
+	return 0
+}
+
+# Compile the source code from the src directory into the java byte code 
+# into the bin directory
+#
+# @returns 0 if successful, 1 otherwise
+compile() {
+	STRUCTURE_PATH=$(realpath $CLASSPATH/.. 2> /dev/null)
+	SOURCE_PATH=$(realpath $CLASSPATH/../src 2> /dev/null)
+	BIN_PATH=$(realpath $CLASSPATH 2> /dev/null)
+
+	## Gather any java files within the source directory
+	list=$(find $SOURCE_PATH -name "*.java")
+	
+	if [ -z "$list" ]
+	then
+		echo "[ERROR] No source files to compile."
+		echo "--> ROOT: $STRUCTURE_PATH"
+		echo "--> SOURCE: $SOURCE_PATH"
+		echo "--> CLASSPATH: $BIN_PATH"
+		return 1
+	else 
+		echo "ROOT: $STRUCTURE_PATH"
+		echo " > SOURCE: $SOURCE_PATH"
+		echo " > CLASSPATH: $BIN_PATH"
+		echo "Files:"
+		echo "$(echo $list | tr ' ' '\n' | sed 's/^/ > /')"
+		echo "Compiling..."
+		javac -d $BIN_PATH $list 
+		if [ $? -eq 0 ] 
+		then
+			return 0
+		else
+			return 1
+		fi
+	fi
+}
+
+# Entry point of the program
+#
+# @params $@ - the command line arguments
+# @returns 0 if the program executed successfully, 1 otherwise
+main() {
+	# Check 0 args passed
+	if [ $# -ne 0 ]
+	then
+		print_usage
+		return 1
+	fi
+
+	# Check the binary (classpath) directory
+	check_bin_path
+	if [ $? -ne 0 ]
+	then
+		return 1
+	fi
+	
+	# Check the source directory
+	check_source_path
+	if [ $? -ne 0 ]
+	then
+		return 1
+	fi
+	
+	# Compile the source into the binary directory
+	compile
+	if [ $? -eq 0 ]
+	then
+		return 0
+	else
+		return 1
+	fi
+}
+
+# Start the program
+main $@
+
+# Check if the program ran successfully
+if [ $? -eq 0 ]
 then
-	echo "No source files to compile. Check your classpath is accurately set?"
-	echo "ROOT: $STRUCTURE_PATH"
-	echo "SOURCE: $SOURCE_PATH"
-	echo "CLASSPATH: $BIN_PATH"
-else 
-	echo "ROOT: $STRUCTURE_PATH"
-	echo "SOURCE: $SOURCE_PATH"
-	echo "CLASSPATH: $BIN_PATH"
-	echo "File list:"
-	echo "$(echo $list | tr ' ' '\n')"
-	echo "Compiling..."
-	javac -d $BIN_PATH $list
 	echo "...Complete!"
+else
+	echo "Errors ocurred. See details above."
 fi
-
-exit 0
-
-
diff --git a/jenv b/jenv
--- a/jenv
+++ b/jenv
@@ -8,17 +8,17 @@
 # Print usage for the program
 print_usage() {
 	echo "Usage: \"jenv\""
-	exit 1
+	return 1
 }
 
 # Check if the bin (classpath) directory exists
 # 
-# @params $1 - the path of the classpath folder
-# @returns 0 if the bin folder exists
+# @params $1 - the path of a bin/classpath folder
+# @returns 0 if the classpath directory exists conventionally
 # @returns 1 if $CLASSPATH is null
 # @returns 2 if $CLASSPATH is not a directory
-# @retuens 3 if $CLASSPATH is not named bin
-check_classpath() {
+# @returns 3 if $CLASSPATH is not named bin
+check_bin_path() {
 	# Check if CLASSPATH is empty
 	if [ -z $1 ]
 	then
@@ -37,9 +37,9 @@ check_classpath() {
 	return 0
 }
 
-# Check if the source directory exists
+# Check if a source directory exists
 # 
-# @params $1 - the path of the source folder
+# @params $1 - the path of a source folder
 # @returns 0 if the source folder exists, 1 otherwise
 check_source_path() {
 	# Check if source path is a directory
@@ -50,47 +50,77 @@ check_source_path() {
 	return 0
 }
 
-# Check more than 1 argument was passed
-if [ $# -gt 0 ]
-then
-	print_usage
-fi
+# Entry point of the program
+# 
+# @params $@ - the command line arguments
+# @returns 0 if the program executed successfully, 1 otherwise
+main() {
+	# Check 0 args was passed
+	if [ $# -ne 0 ]
+	then
+		print_usage
+		return 1
+	fi
 
+	# Program can start! Proper usage.
+	# --------------------------------
 
-# Index environment locations
-STRUCTURE_PATH=$(realpath $CLASSPATH/..)
-SOURCE_PATH=$(realpath $STRUCTURE_PATH/src)
+	# Index important locations
+	STRUCTURE_PATH=$(realpath $CLASSPATH/.. 2> /dev/null)
+	SOURCE_PATH=$(realpath $STRUCTURE_PATH/src 2> /dev/null)
+	BIN_PATH=$(realpath $CLASSPATH 2> /dev/null)
+	
+	check_bin_path $BIN_PATH
+	bin_return=$?
 
-check_classpath $CLASSPATH
-bin_return=$?
+	check_source_path $SOURCE_PATH
+	src_return=$?
+	
 
-check_source_path $SOURCE_PATH
-src_return=$?
+	# Display results
+	# Display Classpath results
+	if [ $bin_return -ne 0 ]
+	then
+		echo "[ERROR] CLASSPATH: '$CLASSPATH'"
+		if [ $bin_return -eq 1 ]; then echo "--> CLASSPATH is not set."; fi
+		if [ $bin_return -eq 2 ]; then echo "--> CLASSPATH is not a directory."; fi
+		if [ $bin_return -eq 3 ]; then echo "--> CLASSPATH is not named 'bin' conventionally."; fi
+		return 1
+	else
+		echo "[OK] CLASSPATH: '$CLASSPATH'"
+	fi
 
-if [ $bin_return -ne 0 ]
-then
-	echo "[ERR] CLASSPATH: '$CLASSPATH' ($bin_return)"
-	if [ $bin_return -eq 1 ]; then echo "--> CLASSPATH is not set."; fi
-	if [ $bin_return -eq 2 ]; then echo "--> CLASSPATH is not a directory."; fi
-	if [ $bin_return -eq 3 ]; then echo "--> CLASSPATH is not named 'bin' conventionally."; fi
-	exit 1
-else
-	echo "[OK] CLASSPATH: $CLASSPATH"
-fi
-if [ $src_return -ne 0 ]
-then
-	echo "[ERR] SOURCE: '$SOURCE_PATH' ($src_return)"
-	if [ $src_return -eq 1 ]; then echo "--> source folder does not exist."; fi
-	exit 1
-else
-	echo "[OK] SOURCE: $SOURCE_PATH"
-fi
-if [ $bin_return -eq 0 ] && [ $src_return -eq 0 ]
-then
-	echo "[OK] ROOT: '$STRUCTURE_PATH'"
+	# Display Source results
+	if [ $src_return -ne 0 ]
+	then
+		echo "[ERROR] SOURCE: '$SOURCE_PATH'"
+		if [ $src_return -eq 1 ]; then echo "--> source folder does not exist."; fi
+		return 1
+	else
+		echo "[OK] SOURCE: '$SOURCE_PATH'"
+	fi
+
+	# Display Summary Results
+	if [ $bin_return -eq 0 ] && [ $src_return -eq 0 ]
+	then
+		echo "[OK] ROOT: '$STRUCTURE_PATH'"
+	else
+		echo "[ERROR] '$STRUCTURE_PATH' is not a valid root directory for a java project."
+		return 1
+	fi
+}
+
+# Start the program
+main $@
+
+# Check if the program ran successfully
+if [ $? -eq 0 ]
+then 
 	echo "All good to go!"
 else
-	echo "[ERR] '$STRUCTURE_PATH' is not a valid root directory for a java project."
-	exit 1
+	echo "Errors occurred. See details above."
 fi
+
+
+
 
diff --git a/jsrc b/jsrc
--- a/jsrc
+++ b/jsrc
@@ -9,7 +9,7 @@
 
 # Print usage for the program
 print_usage() {
-	echo "Usage: \". jsrc <source_path>\""
+	echo "Usage: \"source jsrc <source_path>\""
 	return 1
 }
 
@@ -21,15 +21,15 @@ check_source_path() {
 	#Check if source path is a directory 
 	if [ ! -d $1 ]
 	then
-		echo "$1 is not a directory."
 		print_usage
+		echo "[ERROR] $1 is not a directory."
 		return 1
 	fi
 	
 	if [ "${1: -4}" != "/src" ]
 	then
-		echo "$1 must be a folder named src."
-		echo "You should initiate jsrc on your source folder."
+		echo "[ERROR] $1 must be a folder named src."
+		echo "--> You should initiate jsrc on your source folder."
 		return 1
 	fi
 
@@ -55,11 +55,11 @@ check_bin_path() {
 			mkdir $BIN_PATH
 			if [ $? -ne 0 ] # Check for mkdir success
 			then
-				echo "Could not create $BIN_PATH. Privilege error."
+				echo "[ERROR] Could not create $BIN_PATH. Privilege error."
 				return 1
 			fi
 		else
-			echo "You must obey standard conventions to use this program."
+			echo "[ERROR] You must obey standard conventions to use this program."
 			return 1
 		fi
 	fi
@@ -67,36 +67,83 @@ check_bin_path() {
 	return 0
 }
 
-# Check more than 1 argument was passed
-if [ $# -gt 1 ]
-then
-	print_usage
-else
-	# Index important locations
+# Checks if the program being called is sourced
+#
+# @returns 0 if the program is sourced, 1 otherwise 
+check_program_sourced() {
+	if [[ "${BASH_SOURCE[0]}" != "${0}" ]]
+	then
+		return 0
+	else
+		print_usage
+		return 1
+	fi
+}
+
+# Start of the program (functioned)
+#
+# @params $@ - the command line arguments	
+# @returns 0 if the program executed successfully, 1 otherwise
+main() {
+	# Check <= 1 args passed
+	if [ $# -gt 1 ]
+	then
+		print_usage
+		return 1
+	fi
+	
+	# Check if the program is sourced
+	check_program_sourced
+	if [ $? -ne 0 ]
+	then
+		return 1
+	fi
+
+	# Program can start! Proper usage.
+	# --------------------------------
+
+	# Index environment locations
 	if [ "$#" -eq 0 ] # Check if a source path was passed
 	then # No arguments were passed
-		SOURCE_PATH=$(realpath .)
+		SOURCE_PATH=$(realpath . 2> /dev/null)
 	else # 1 argument
-		SOURCE_PATH=$(realpath $1)
+		SOURCE_PATH=$(realpath $1 2> /dev/null)
 	fi
-	STRUCTURE_PATH=$(realpath ..)
-	BIN_PATH=$(realpath ${SOURCE_PATH}/../bin)
+	STRUCTURE_PATH=$(realpath ${SOURCE_PATH}/.. 2> /dev/null)
+	BIN_PATH=$(realpath ${SOURCE_PATH}/../bin 2> /dev/null)
 	
+	# Check for a valid source path
 	check_source_path $SOURCE_PATH
        	src_exists=$?
-	if [ $src_exists -eq 0 ]
+	if [ $src_exists -ne 0 ]
 	then
-		check_bin_path $BIN_PATH
-		bin_exists=$? 
-		if [ $bin_exists -eq 0 ]
-		then
-			export CLASSPATH=$BIN_PATH
-			echo "ROOT: $STRUCTURE_PATH"
-			echo "SOURCE: $SOURCE_PATH"
-			echo "CLASSPATH: $CLASSPATH"
-			echo "... Complete!"
-		fi
+		return 1
 	fi
+
+	# Check for a valid bin path
+	check_bin_path $BIN_PATH
+	bin_exists=$? 
+	if [ $bin_exists -ne 0 ]
+	then
+		return 1
+	fi
+
+	export CLASSPATH=$BIN_PATH
+	return 0
+} 
+
+# Start the program
+main $@
+
+# Check if the program ran succesfully
+if [ $? -eq 0 ]
+then
+	echo "ROOT: $STRUCTURE_PATH"
+	echo "SOURCE: $SOURCE_PATH"
+	echo "CLASSPATH: $CLASSPATH"
+	echo "...Complete!"
+else
+	echo "Error occurred. See details above."
 fi 
 
 
